/* The following code was generated by JFlex 1.3.5 on 07/05/19 11:23 */

package fr.n7.stl.block;
import java_cup.runtime.ComplexSymbolFactory;
import java_cup.runtime.ComplexSymbolFactory.Location;
import java_cup.runtime.Symbol;
import java.lang.*;
import java.io.InputStreamReader;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.3.5
 * on 07/05/19 11:23 from the specification file
 * <tt>file:/home/imoumen/Bureau/Downloads/be block/fr.n7.stl.block/lexer.jflex</tt>
 */
public class Lexer implements sym, java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  final public static int YYEOF = -1;

  /** initial size of the lookahead buffer */
  final private static int YY_BUFFERSIZE = 16384;

  /** lexical states */
  final public static int CODESEG = 1;
  final public static int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  final private static String yycmap_packed = 
    "\11\15\1\3\1\2\1\0\1\3\1\1\16\15\4\0\1\3\1\24"+
    "\1\11\1\0\1\17\1\32\1\34\1\13\1\35\1\36\1\10\1\30"+
    "\1\21\1\31\1\6\1\7\1\4\11\5\1\22\1\20\1\26\1\25"+
    "\1\27\1\23\1\0\22\16\1\64\7\16\1\41\1\12\1\42\1\0"+
    "\1\17\1\0\1\62\1\66\1\43\1\53\1\52\1\54\1\65\1\63"+
    "\1\60\2\17\1\61\1\57\1\45\1\44\1\51\1\17\1\55\1\46"+
    "\1\47\1\56\1\67\1\70\1\71\1\50\1\17\1\37\1\33\1\40"+
    "\1\0\41\15\2\0\4\17\4\0\1\17\2\0\1\15\7\0\1\17"+
    "\4\0\1\17\5\0\27\16\1\0\7\16\30\17\1\0\10\17\1\16"+
    "\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16"+
    "\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16"+
    "\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16"+
    "\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16"+
    "\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16"+
    "\1\17\1\16\1\17\1\16\2\17\1\16\1\17\1\16\1\17\1\16"+
    "\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16"+
    "\2\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16"+
    "\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16"+
    "\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16"+
    "\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16"+
    "\1\17\1\16\1\17\1\16\1\17\1\16\1\17\2\16\1\17\1\16"+
    "\1\17\1\16\3\17\2\16\1\17\1\16\1\17\2\16\1\17\3\16"+
    "\2\17\4\16\1\17\2\16\1\17\3\16\3\17\2\16\1\17\2\16"+
    "\1\17\1\16\1\17\1\16\1\17\2\16\1\17\1\16\2\17\1\16"+
    "\1\17\2\16\1\17\3\16\1\17\1\16\1\17\2\16\3\17\1\16"+
    "\7\17\1\16\2\17\1\16\2\17\1\16\2\17\1\16\1\17\1\16"+
    "\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16"+
    "\1\17\1\16\2\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16"+
    "\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16"+
    "\2\17\1\16\2\17\1\16\1\17\3\16\1\17\1\16\1\17\1\16"+
    "\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16"+
    "\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16"+
    "\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16"+
    "\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16"+
    "\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16"+
    "\1\17\1\16\1\17\1\16\7\17\2\16\1\17\2\16\2\17\1\16"+
    "\1\17\4\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16"+
    "\163\17\4\0\14\17\16\0\5\17\7\0\1\17\1\0\1\17\21\0"+
    "\160\15\1\16\1\17\1\16\2\17\1\0\1\16\1\17\2\0\4\17"+
    "\10\0\1\16\1\0\3\16\1\0\1\16\1\0\2\16\1\17\21\16"+
    "\1\0\11\16\43\17\1\16\2\17\3\16\3\17\1\16\1\17\1\16"+
    "\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16"+
    "\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16"+
    "\5\17\1\16\1\17\1\0\1\16\1\17\2\16\2\17\63\16\60\17"+
    "\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17"+
    "\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17"+
    "\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17"+
    "\1\16\1\17\1\16\1\17\1\0\5\15\2\0\1\16\1\17\1\16"+
    "\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16"+
    "\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16"+
    "\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16"+
    "\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16"+
    "\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16"+
    "\1\17\2\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16"+
    "\1\17\1\16\1\17\1\16\2\17\1\16\1\17\1\16\1\17\1\16"+
    "\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16"+
    "\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16"+
    "\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16"+
    "\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16"+
    "\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16"+
    "\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16"+
    "\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16"+
    "\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16"+
    "\1\17\1\16\1\17\11\0\46\16\2\0\1\17\7\0\47\17\7\0"+
    "\1\17\1\0\55\15\1\0\1\15\1\0\2\15\1\0\2\15\1\0"+
    "\1\15\10\0\33\17\5\0\3\17\15\0\5\15\6\0\1\17\4\0"+
    "\13\15\5\0\53\17\37\15\4\0\2\17\1\15\143\17\1\0\1\17"+
    "\10\15\1\0\6\15\2\17\2\15\1\0\4\15\2\17\12\15\3\17"+
    "\2\0\1\17\17\0\1\15\1\17\1\15\36\17\33\15\2\0\131\17"+
    "\13\15\1\17\16\0\12\15\41\17\11\15\2\17\4\0\1\17\5\0"+
    "\26\17\4\15\1\17\11\15\1\17\3\15\1\17\5\15\22\0\31\17"+
    "\3\15\104\0\1\17\1\0\13\17\67\0\33\15\1\0\4\15\66\17"+
    "\3\15\1\17\22\15\1\17\7\15\12\17\2\15\2\0\12\15\1\0"+
    "\7\17\1\0\7\17\1\0\3\15\1\0\10\17\2\0\2\17\2\0"+
    "\26\17\1\0\7\17\1\0\1\17\3\0\4\17\2\0\1\15\1\17"+
    "\7\15\2\0\2\15\2\0\3\15\1\17\10\0\1\15\4\0\2\17"+
    "\1\0\3\17\2\15\2\0\12\15\4\17\7\0\1\17\5\0\3\15"+
    "\1\0\6\17\4\0\2\17\2\0\26\17\1\0\7\17\1\0\2\17"+
    "\1\0\2\17\1\0\2\17\2\0\1\15\1\0\5\15\4\0\2\15"+
    "\2\0\3\15\3\0\1\15\7\0\4\17\1\0\1\17\7\0\14\15"+
    "\3\17\1\15\13\0\3\15\1\0\11\17\1\0\3\17\1\0\26\17"+
    "\1\0\7\17\1\0\2\17\1\0\5\17\2\0\1\15\1\17\10\15"+
    "\1\0\3\15\1\0\3\15\2\0\1\17\17\0\2\17\2\15\2\0"+
    "\12\15\1\0\1\17\17\0\3\15\1\0\10\17\2\0\2\17\2\0"+
    "\26\17\1\0\7\17\1\0\2\17\1\0\5\17\2\0\1\15\1\17"+
    "\7\15\2\0\2\15\2\0\3\15\10\0\2\15\4\0\2\17\1\0"+
    "\3\17\2\15\2\0\12\15\1\0\1\17\20\0\1\15\1\17\1\0"+
    "\6\17\3\0\3\17\1\0\4\17\3\0\2\17\1\0\1\17\1\0"+
    "\2\17\3\0\2\17\3\0\3\17\3\0\14\17\4\0\5\15\3\0"+
    "\3\15\1\0\4\15\2\0\1\17\6\0\1\15\16\0\12\15\11\0"+
    "\1\17\7\0\3\15\1\0\10\17\1\0\3\17\1\0\27\17\1\0"+
    "\12\17\1\0\5\17\3\0\1\17\7\15\1\0\3\15\1\0\4\15"+
    "\7\0\2\15\1\0\2\17\6\0\2\17\2\15\2\0\12\15\22\0"+
    "\2\15\1\0\10\17\1\0\3\17\1\0\27\17\1\0\12\17\1\0"+
    "\5\17\2\0\1\15\1\17\7\15\1\0\3\15\1\0\4\15\7\0"+
    "\2\15\7\0\1\17\1\0\2\17\2\15\2\0\12\15\1\0\2\17"+
    "\17\0\2\15\1\0\10\17\1\0\3\17\1\0\51\17\2\0\1\17"+
    "\7\15\1\0\3\15\1\0\4\15\1\17\10\0\1\15\10\0\2\17"+
    "\2\15\2\0\12\15\12\0\6\17\2\0\2\15\1\0\22\17\3\0"+
    "\30\17\1\0\11\17\1\0\1\17\2\0\7\17\3\0\1\15\4\0"+
    "\6\15\1\0\1\15\1\0\10\15\22\0\2\15\15\0\60\17\1\15"+
    "\2\17\7\15\4\0\10\17\10\15\1\0\12\15\47\0\2\17\1\0"+
    "\1\17\2\0\2\17\1\0\1\17\2\0\1\17\6\0\4\17\1\0"+
    "\7\17\1\0\3\17\1\0\1\17\1\0\1\17\2\0\2\17\1\0"+
    "\4\17\1\15\2\17\6\15\1\0\2\15\1\17\2\0\5\17\1\0"+
    "\1\17\1\0\6\15\2\0\12\15\2\0\4\17\40\0\1\17\27\0"+
    "\2\15\6\0\12\15\13\0\1\15\1\0\1\15\1\0\1\15\4\0"+
    "\2\15\10\17\1\0\44\17\4\0\24\15\1\0\2\15\5\17\13\15"+
    "\1\0\44\15\11\0\1\15\71\0\53\17\24\15\1\17\12\15\6\0"+
    "\6\17\4\15\4\17\3\15\1\17\3\15\2\17\7\15\3\17\4\15"+
    "\15\17\14\15\1\17\17\15\2\0\46\16\1\0\1\16\5\0\1\16"+
    "\2\0\53\17\1\0\u014d\17\1\0\4\17\2\0\7\17\1\0\1\17"+
    "\1\0\4\17\2\0\51\17\1\0\4\17\2\0\41\17\1\0\4\17"+
    "\2\0\7\17\1\0\1\17\1\0\4\17\2\0\17\17\1\0\71\17"+
    "\1\0\4\17\2\0\103\17\2\0\3\15\40\0\20\17\20\0\125\17"+
    "\14\0\u026c\17\2\0\21\17\1\0\32\17\5\0\113\17\3\0\3\17"+
    "\17\0\15\17\1\0\4\17\3\15\13\0\22\17\3\15\13\0\22\17"+
    "\2\15\14\0\15\17\1\0\3\17\1\0\2\15\14\0\64\17\40\15"+
    "\3\0\1\17\3\0\2\17\1\15\2\0\12\15\41\0\3\15\2\0"+
    "\12\15\6\0\130\17\10\0\51\17\1\15\1\17\5\0\106\17\12\0"+
    "\35\17\3\0\14\15\4\0\14\15\12\0\12\15\36\17\2\0\5\17"+
    "\13\0\54\17\4\0\21\15\7\17\2\15\6\0\12\15\46\0\27\17"+
    "\5\15\4\0\65\17\12\15\1\0\35\15\2\0\13\15\6\0\12\15"+
    "\15\0\1\17\130\0\5\15\57\17\21\15\7\17\4\0\12\15\21\0"+
    "\11\15\14\0\3\15\36\17\15\15\2\17\12\15\54\17\16\15\14\0"+
    "\44\17\24\15\10\0\12\15\3\0\3\17\12\15\44\17\122\0\3\15"+
    "\1\0\25\15\4\17\1\15\4\17\3\15\2\17\11\0\300\17\47\15"+
    "\25\0\4\15\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17"+
    "\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17"+
    "\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17"+
    "\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17"+
    "\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17"+
    "\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17"+
    "\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17"+
    "\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17"+
    "\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17"+
    "\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17"+
    "\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17"+
    "\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17"+
    "\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17"+
    "\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17"+
    "\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17"+
    "\1\16\11\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17"+
    "\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17"+
    "\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17"+
    "\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17"+
    "\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17"+
    "\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17"+
    "\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17"+
    "\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17"+
    "\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17"+
    "\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\11\17"+
    "\10\16\6\17\2\0\6\16\2\0\10\17\10\16\10\17\10\16\6\17"+
    "\2\0\6\16\2\0\10\17\1\0\1\16\1\0\1\16\1\0\1\16"+
    "\1\0\1\16\10\17\10\16\16\17\2\0\65\17\1\0\2\17\4\16"+
    "\1\17\1\0\1\17\3\0\3\17\1\0\2\17\4\16\1\17\3\0"+
    "\4\17\2\0\2\17\4\16\4\0\10\17\5\16\5\0\3\17\1\0"+
    "\2\17\4\16\1\17\16\0\5\15\32\0\5\15\20\0\2\17\23\0"+
    "\1\17\13\0\5\15\5\0\6\15\1\0\1\17\15\0\1\17\20\0"+
    "\15\17\3\0\33\17\25\0\15\15\4\0\1\15\3\0\14\15\21\0"+
    "\1\16\4\0\1\16\2\0\1\17\3\16\2\17\3\16\1\17\1\0"+
    "\1\16\3\0\5\16\6\0\1\16\1\0\1\16\1\0\1\16\1\0"+
    "\4\16\1\0\1\17\4\16\6\17\2\0\2\17\2\16\5\0\1\16"+
    "\4\17\4\0\1\17\21\0\20\16\23\17\1\16\5\17\u032d\0\32\14"+
    "\u0730\0\57\16\1\0\57\17\1\0\1\16\1\17\3\16\2\17\1\16"+
    "\1\17\1\16\1\17\1\16\1\17\4\16\1\17\1\16\2\17\1\16"+
    "\10\17\3\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16"+
    "\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16"+
    "\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16"+
    "\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16"+
    "\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16"+
    "\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16"+
    "\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16"+
    "\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16"+
    "\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16"+
    "\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16"+
    "\2\17\6\0\1\16\1\17\1\16\1\17\3\15\1\16\1\17\14\0"+
    "\46\17\1\0\1\17\5\0\1\17\2\0\70\17\7\0\1\17\17\0"+
    "\1\15\27\17\11\0\7\17\1\0\7\17\1\0\7\17\1\0\7\17"+
    "\1\0\7\17\1\0\7\17\1\0\7\17\1\0\7\17\1\0\40\15"+
    "\57\0\1\17\u01d5\0\3\17\31\0\11\17\6\15\1\0\5\17\2\0"+
    "\5\17\4\0\126\17\2\0\2\15\2\0\3\17\1\0\132\17\1\0"+
    "\4\17\5\0\51\17\3\0\136\17\21\0\33\17\65\0\20\17\u0200\0"+
    "\u19b6\17\112\0\u51cd\17\63\0\u048d\17\103\0\56\17\2\0\u010d\17\3\0"+
    "\20\17\12\15\2\17\24\0\1\16\1\17\1\16\1\17\1\16\1\17"+
    "\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17"+
    "\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17"+
    "\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17"+
    "\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\2\17"+
    "\1\15\4\0\12\15\1\0\1\17\1\16\1\17\1\16\1\17\1\16"+
    "\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16"+
    "\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\7\0"+
    "\1\15\120\17\2\15\45\0\11\17\2\0\1\16\1\17\1\16\1\17"+
    "\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\3\17"+
    "\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17"+
    "\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17"+
    "\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17"+
    "\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17"+
    "\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17"+
    "\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\1\17"+
    "\1\16\12\17\1\16\1\17\1\16\1\17\2\16\1\17\1\16\1\17"+
    "\1\16\1\17\1\16\1\17\1\16\2\17\2\0\1\16\1\17\1\16"+
    "\1\17\1\0\1\16\1\17\1\16\1\17\14\0\1\16\1\17\1\16"+
    "\1\17\1\16\1\17\1\16\1\17\1\16\1\17\1\16\115\0\12\17"+
    "\1\15\3\17\1\15\4\17\1\15\27\17\5\15\20\0\1\17\7\0"+
    "\64\17\14\0\2\15\62\17\21\15\13\0\12\15\6\0\22\15\6\17"+
    "\3\0\1\17\4\0\12\15\34\17\10\15\2\0\27\17\15\15\14\0"+
    "\35\17\3\0\4\15\57\17\16\15\16\0\1\17\12\15\46\0\51\17"+
    "\16\15\11\0\3\17\1\15\10\17\2\15\2\0\12\15\6\0\27\17"+
    "\3\0\1\17\1\15\4\0\60\17\1\15\1\17\3\15\2\17\2\15"+
    "\5\17\2\15\1\17\1\15\1\17\30\0\3\17\2\0\13\17\5\15"+
    "\2\0\3\17\2\15\12\0\6\17\2\0\6\17\2\0\6\17\11\0"+
    "\7\17\1\0\7\17\221\0\43\17\10\15\1\0\2\15\2\0\12\15"+
    "\6\0\u2ba4\17\14\0\27\17\4\0\61\17\u2104\0\u016e\17\2\0\152\17"+
    "\46\0\7\17\14\0\5\17\5\0\1\17\1\15\12\17\1\0\15\17"+
    "\1\0\5\17\1\0\1\17\1\0\2\17\1\0\2\17\1\0\154\17"+
    "\41\0\u016b\17\22\0\100\17\2\0\66\17\50\0\15\17\3\0\20\15"+
    "\20\0\7\15\14\0\2\17\30\0\3\17\31\0\1\17\6\0\5\17"+
    "\1\0\207\17\2\0\1\15\4\0\1\17\13\0\12\15\7\0\32\16"+
    "\4\0\1\17\1\0\32\17\13\0\131\17\3\0\6\17\2\0\6\17"+
    "\2\0\6\17\2\0\3\17\3\0\2\17\3\0\2\17\22\0\3\15"+
    "\4\0";

  /** 
   * Translates characters to character classes
   */
  final private static char [] yycmap = yy_unpack_cmap(yycmap_packed);

  /** 
   * Translates a state to a row index in the transition table
   */
  final private static int yy_rowMap [] = { 
        0,    58,   116,   174,   116,   232,   290,   116,   348,   116, 
      406,   464,   522,   580,   116,   116,   116,   116,   638,   696, 
      754,   812,   870,   928,   116,   986,  1044,   116,   116,   116, 
      116,   116,   116,  1102,  1160,  1218,  1276,  1334,  1392,  1450, 
     1508,  1566,  1624,  1682,  1740,  1798,  1856,  1914,  1972,  2030, 
      406,   116,  2088,  2146,  2204,   116,   116,   116,   116,   116, 
      116,   116,   116,  2262,  2320,  2378,  2436,  2494,  2552,  2610, 
     2668,  2726,  2784,  2842,  2900,  2958,  3016,  3074,  3132,  3190, 
     3248,  3306,  3364,   580,  3422,  3480,  3538,  3596,  3654,  3712, 
      116,  3770,  3828,   406,   116,  3886,  3944,  4002,   580,  4060, 
      580,  4118,  4176,  4234,  4292,  4350,  4408,  4466,  4524,  4582, 
     4640,   580,  4698,  4756,  4814,  4872,  4930,  4988,  5046,  5104, 
     5162,  5220,  5278,  5336,  5394,   580,   580,  5452,  5510,  5568, 
      580,  5626,  5684,  5742,  5800,   580,   580,  5858,  5916,  5974, 
     6032,  6090,  6148,  6206,  6264,  6322,  6380,   580,  6438,   580, 
      580,  6496,  6554,  6612,  6670,   580,  6728,  6786,  6844,   580, 
      580,   580,  6902,  6960,  7018,  7076,  7134,  7192,   580,   580, 
      580,  7250,  7308,  7366,   580,  7424,   580,  7482,  7540,  7598, 
      522,  7656,   580,  7714,   580,   580,  7772,  7830,  7888,   580, 
     7946,  8004,  8062,   580,   580,   580,  8120,   580
  };

  /** 
   * The packed transition table of the DFA (part 0)
   */
  final private static String yy_packed0 = 
    "\1\3\1\4\2\5\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\1\3\1\14\1\15\1\3\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\1\16\1\43\1\44\1\45\1\16"+
    "\1\46\1\47\1\16\1\50\1\51\2\16\1\52\1\16"+
    "\1\53\1\16\1\54\1\16\1\55\1\56\1\57\1\16"+
    "\72\3\74\0\1\5\75\0\1\60\67\0\2\7\1\60"+
    "\72\0\1\61\1\62\61\0\11\63\1\64\1\65\57\63"+
    "\12\66\1\67\57\66\4\0\2\15\7\0\3\15\23\0"+
    "\27\15\4\0\2\16\7\0\3\16\23\0\27\16\25\0"+
    "\1\70\71\0\1\71\71\0\1\72\71\0\1\73\74\0"+
    "\1\74\72\0\1\75\73\0\1\76\72\0\1\77\41\0"+
    "\2\16\7\0\3\16\23\0\1\16\1\100\14\16\1\101"+
    "\1\16\1\102\6\16\4\0\2\16\7\0\3\16\23\0"+
    "\7\16\1\103\3\16\1\104\13\16\4\0\2\16\7\0"+
    "\3\16\23\0\2\16\1\105\1\16\1\106\22\16\4\0"+
    "\2\16\7\0\3\16\23\0\5\16\1\107\4\16\1\110"+
    "\14\16\4\0\2\16\7\0\3\16\23\0\12\16\1\111"+
    "\1\112\13\16\4\0\2\16\7\0\3\16\23\0\2\16"+
    "\1\113\13\16\1\114\7\16\1\115\4\0\2\16\7\0"+
    "\3\16\23\0\3\16\1\116\11\16\1\117\1\120\1\121"+
    "\7\16\4\0\2\16\7\0\3\16\23\0\7\16\1\122"+
    "\17\16\4\0\2\16\7\0\3\16\23\0\2\16\1\123"+
    "\6\16\1\124\2\16\1\125\12\16\4\0\2\16\7\0"+
    "\3\16\23\0\23\16\1\126\3\16\4\0\2\15\7\0"+
    "\3\15\23\0\4\15\1\127\22\15\4\0\2\16\7\0"+
    "\3\16\23\0\1\16\1\130\25\16\4\0\2\16\7\0"+
    "\3\16\23\0\1\16\1\131\25\16\4\0\2\16\7\0"+
    "\3\16\23\0\20\16\1\132\6\16\4\0\1\133\1\134"+
    "\64\0\1\61\1\4\1\5\67\61\10\62\1\135\61\62"+
    "\11\63\1\136\1\65\57\63\13\0\1\137\70\0\1\66"+
    "\63\0\2\16\7\0\3\16\23\0\2\16\1\140\24\16"+
    "\4\0\2\16\7\0\3\16\23\0\17\16\1\141\7\16"+
    "\4\0\2\16\7\0\3\16\23\0\17\16\1\142\7\16"+
    "\4\0\2\16\7\0\3\16\23\0\25\16\1\143\1\16"+
    "\4\0\2\16\7\0\3\16\23\0\16\16\1\144\10\16"+
    "\4\0\2\16\7\0\3\16\23\0\10\16\1\145\16\16"+
    "\4\0\2\16\7\0\3\16\23\0\12\16\1\146\4\16"+
    "\1\147\7\16\4\0\2\16\7\0\3\16\23\0\6\16"+
    "\1\150\20\16\4\0\2\16\7\0\3\16\23\0\13\16"+
    "\1\151\13\16\4\0\2\16\7\0\3\16\23\0\1\16"+
    "\1\152\13\16\1\153\11\16\4\0\2\16\7\0\3\16"+
    "\23\0\23\16\1\154\3\16\4\0\2\16\7\0\3\16"+
    "\23\0\13\16\1\155\13\16\4\0\2\16\7\0\3\16"+
    "\23\0\3\16\1\156\23\16\4\0\2\16\7\0\3\16"+
    "\23\0\4\16\1\157\22\16\4\0\2\16\7\0\3\16"+
    "\23\0\4\16\1\160\22\16\4\0\2\16\7\0\3\16"+
    "\23\0\2\16\1\161\24\16\4\0\2\16\7\0\3\16"+
    "\23\0\1\16\1\162\25\16\4\0\2\16\7\0\3\16"+
    "\23\0\16\16\1\163\10\16\4\0\2\16\7\0\3\16"+
    "\23\0\4\16\1\164\22\16\4\0\2\16\7\0\3\16"+
    "\23\0\4\16\1\165\22\16\4\0\2\16\7\0\3\16"+
    "\23\0\6\16\1\166\20\16\4\0\2\16\7\0\3\16"+
    "\23\0\3\16\1\167\23\16\4\0\2\15\7\0\3\15"+
    "\23\0\12\15\1\170\14\15\4\0\2\16\7\0\3\16"+
    "\23\0\1\16\1\171\25\16\4\0\2\16\7\0\3\16"+
    "\23\0\15\16\1\172\11\16\4\0\2\16\7\0\3\16"+
    "\23\0\15\16\1\173\11\16\4\0\2\134\64\0\7\62"+
    "\1\5\1\135\61\62\4\0\2\16\7\0\3\16\23\0"+
    "\3\16\1\174\23\16\4\0\2\16\7\0\3\16\23\0"+
    "\3\16\1\175\23\16\4\0\2\16\7\0\3\16\23\0"+
    "\12\16\1\176\14\16\4\0\2\16\7\0\3\16\23\0"+
    "\16\16\1\177\10\16\4\0\2\16\7\0\3\16\23\0"+
    "\13\16\1\200\13\16\4\0\2\16\7\0\3\16\23\0"+
    "\4\16\1\201\22\16\4\0\2\16\7\0\3\16\23\0"+
    "\7\16\1\202\17\16\4\0\2\16\7\0\3\16\23\0"+
    "\7\16\1\203\17\16\4\0\2\16\7\0\3\16\23\0"+
    "\4\16\1\204\22\16\4\0\2\16\7\0\3\16\23\0"+
    "\2\16\1\205\21\16\1\206\2\16\4\0\2\16\7\0"+
    "\3\16\23\0\16\16\1\207\10\16\4\0\2\16\7\0"+
    "\3\16\23\0\14\16\1\210\12\16\4\0\2\16\7\0"+
    "\3\16\23\0\7\16\1\211\17\16\4\0\2\16\7\0"+
    "\3\16\23\0\7\16\1\212\17\16\4\0\2\16\7\0"+
    "\3\16\23\0\17\16\1\213\7\16\4\0\2\16\7\0"+
    "\3\16\23\0\17\16\1\214\7\16\4\0\2\16\7\0"+
    "\3\16\23\0\3\16\1\215\23\16\4\0\2\16\7\0"+
    "\3\16\23\0\13\16\1\216\13\16\4\0\2\16\7\0"+
    "\3\16\23\0\7\16\1\217\17\16\4\0\2\16\7\0"+
    "\3\16\23\0\16\16\1\220\10\16\4\0\2\16\7\0"+
    "\3\16\23\0\4\16\1\221\22\16\4\0\2\15\7\0"+
    "\3\15\23\0\15\15\1\222\11\15\4\0\2\16\7\0"+
    "\3\16\23\0\16\16\1\223\10\16\4\0\2\16\7\0"+
    "\3\16\23\0\10\16\1\224\16\16\4\0\2\16\7\0"+
    "\3\16\23\0\16\16\1\225\10\16\4\0\2\16\7\0"+
    "\3\16\23\0\4\16\1\226\22\16\4\0\2\16\7\0"+
    "\3\16\23\0\3\16\1\227\23\16\4\0\2\16\7\0"+
    "\3\16\23\0\1\230\26\16\4\0\2\16\7\0\3\16"+
    "\23\0\15\16\1\231\11\16\4\0\2\16\7\0\3\16"+
    "\23\0\10\16\1\232\16\16\4\0\2\16\7\0\3\16"+
    "\23\0\7\16\1\233\17\16\4\0\2\16\7\0\3\16"+
    "\23\0\4\16\1\234\22\16\4\0\2\16\7\0\3\16"+
    "\23\0\17\16\1\235\7\16\4\0\2\16\7\0\3\16"+
    "\23\0\15\16\1\236\11\16\4\0\2\16\7\0\3\16"+
    "\23\0\2\16\1\237\24\16\4\0\2\16\7\0\3\16"+
    "\23\0\16\16\1\240\10\16\4\0\2\16\7\0\3\16"+
    "\23\0\4\16\1\241\22\16\4\0\2\16\7\0\3\16"+
    "\23\0\7\16\1\242\17\16\4\0\2\16\7\0\3\16"+
    "\23\0\12\16\1\243\14\16\4\0\2\16\7\0\3\16"+
    "\23\0\12\16\1\244\14\16\4\0\2\16\7\0\3\16"+
    "\23\0\7\16\1\245\17\16\4\0\2\16\7\0\3\16"+
    "\23\0\12\16\1\246\14\16\4\0\2\15\7\0\3\15"+
    "\23\0\2\15\1\247\24\15\4\0\2\16\7\0\3\16"+
    "\23\0\7\16\1\250\17\16\4\0\2\16\7\0\3\16"+
    "\23\0\7\16\1\251\17\16\4\0\2\16\7\0\3\16"+
    "\23\0\4\16\1\252\22\16\4\0\2\16\7\0\3\16"+
    "\23\0\1\253\26\16\4\0\2\16\7\0\3\16\23\0"+
    "\7\16\1\254\17\16\4\0\2\16\7\0\3\16\23\0"+
    "\1\255\26\16\4\0\2\16\7\0\3\16\23\0\4\16"+
    "\1\256\22\16\4\0\2\16\7\0\3\16\23\0\1\257"+
    "\26\16\4\0\2\16\7\0\3\16\23\0\10\16\1\260"+
    "\16\16\4\0\2\16\7\0\3\16\23\0\2\16\1\261"+
    "\24\16\4\0\2\16\7\0\3\16\23\0\11\16\1\262"+
    "\15\16\4\0\2\16\7\0\3\16\23\0\14\16\1\263"+
    "\12\16\4\0\2\16\7\0\3\16\23\0\17\16\1\264"+
    "\7\16\4\0\2\15\7\0\3\15\23\0\22\15\1\265"+
    "\4\15\4\0\2\16\7\0\3\16\23\0\17\16\1\266"+
    "\7\16\4\0\2\16\7\0\3\16\23\0\11\16\1\267"+
    "\15\16\4\0\2\16\7\0\3\16\23\0\4\16\1\270"+
    "\22\16\4\0\2\16\7\0\3\16\23\0\7\16\1\271"+
    "\17\16\4\0\2\16\7\0\3\16\23\0\3\16\1\272"+
    "\23\16\4\0\2\16\7\0\3\16\23\0\17\16\1\273"+
    "\7\16\4\0\2\16\7\0\3\16\23\0\7\16\1\274"+
    "\17\16\4\0\2\16\7\0\3\16\23\0\1\275\26\16"+
    "\4\0\2\16\7\0\3\16\23\0\2\16\1\276\24\16"+
    "\4\0\2\16\7\0\3\16\23\0\7\16\1\277\17\16"+
    "\4\0\2\16\7\0\3\16\23\0\1\300\26\16\4\0"+
    "\2\16\7\0\3\16\23\0\2\16\1\301\24\16\4\0"+
    "\2\16\7\0\3\16\23\0\4\16\1\302\22\16\4\0"+
    "\2\16\7\0\3\16\23\0\10\16\1\303\16\16\4\0"+
    "\2\16\7\0\3\16\23\0\7\16\1\304\17\16\4\0"+
    "\2\16\7\0\3\16\23\0\4\16\1\305\22\16\4\0"+
    "\2\16\7\0\3\16\23\0\3\16\1\306\23\16";

  /** 
   * The transition table of the DFA
   */
  final private static int yytrans [] = yy_unpack();


  /* error codes */
  final private static int YY_UNKNOWN_ERROR = 0;
  final private static int YY_ILLEGAL_STATE = 1;
  final private static int YY_NO_MATCH = 2;
  final private static int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  final private static String YY_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Internal error: unknown state",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private final static byte YY_ATTRIBUTE[] = {
     0,  0,  9,  1,  9,  1,  1,  9,  1,  9,  1,  1,  1,  1,  9,  9, 
     9,  9,  1,  1,  1,  1,  1,  1,  9,  1,  1,  9,  9,  9,  9,  9, 
     9,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  0, 
     0,  0,  0,  9,  0,  0,  0,  9,  9,  9,  9,  9,  9,  9,  9,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  9,  1,  0,  1,  9,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1
  };

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean yy_eof_done;

  /* user code: */
    public Lexer(ComplexSymbolFactory _symbolFactory, java.io.InputStream _inputStream){
		this(_inputStream);
        this.symbolFactory = _symbolFactory;
    }

	public Lexer(ComplexSymbolFactory _symbolFactory, java.io.Reader _reader){
		this(_reader);
        this.symbolFactory = _symbolFactory;
    }
    
    private StringBuffer sb;
    private ComplexSymbolFactory symbolFactory;
    private int csline,cscolumn;

    public Symbol symbol(String name, int code){
		return symbolFactory.newSymbol(name, code,
						new Location(yyline+1,yycolumn+1, yychar), // -yylength()
						new Location(yyline+1,yycolumn+yylength(), yychar+yylength())
				);
    }
    public Symbol symbol(String name, int code, String lexem){
		return symbolFactory.newSymbol(name, code, 
						new Location(yyline+1, yycolumn +1, yychar), 
						new Location(yyline+1,yycolumn+yylength(), yychar+yylength()), lexem);
    }
    
    protected void emit_warning(String message){
    		System.out.println("scanner warning: " + message + " at : 2 "+ 
    			(yyline+1) + " " + (yycolumn+1) + " " + yychar);
    }
    
    protected void emit_error(String message){
    		System.out.println("scanner error: " + message + " at : 2" + 
    			(yyline+1) + " " + (yycolumn+1) + " " + yychar);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the split, compressed DFA transition table.
   *
   * @return the unpacked transition table
   */
  private static int [] yy_unpack() {
    int [] trans = new int[8178];
    int offset = 0;
    offset = yy_unpack(yy_packed0, offset, trans);
    return trans;
  }

  /** 
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the index of the last entry
   */
  private static int yy_unpack(String packed, int offset, int [] trans) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] yy_unpack_cmap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 4422) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }


  /**
   * Closes the input stream.
   */
  final public void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Closes the current stream, and resets the
   * scanner to read from a new input stream.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  final public void yyreset(java.io.Reader reader) throws java.io.IOException {
    yyclose();
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  final public int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  final public void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  final public String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  final public char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  final public int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void yy_do_eof() throws java.io.IOException {
    if (!yy_eof_done) {
      yy_eof_done = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_startRead_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    byte [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      yychar+= yy_markedPos_l-yy_startRead;

      boolean yy_r = false;
      for (yy_currentPos_l = yy_startRead; yy_currentPos_l < yy_markedPos_l;
                                                             yy_currentPos_l++) {
        switch (yy_buffer_l[yy_currentPos_l]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          yy_r = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          yy_r = true;
          break;
        case '\n':
          if (yy_r)
            yy_r = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          yy_r = false;
          yycolumn++;
        }
      }

      if (yy_r) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean yy_peek;
        if (yy_markedPos_l < yy_endRead_l)
          yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        else if (yy_atEOF)
          yy_peek = false;
        else {
          boolean eof = yy_refill();
          yy_markedPos_l = yy_markedPos;
          yy_buffer_l = yy_buffer;
          if (eof) 
            yy_peek = false;
          else 
            yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        }
        if (yy_peek) yyline--;
      }
      yy_action = -1;

      yy_startRead_l = yy_currentPos_l = yy_currentPos = 
                       yy_startRead = yy_markedPos_l;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {

          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action) {

        case 197: 
          {  return symbolFactory.newSymbol("Implements", UL_Implements);  }
        case 199: break;
        case 9: 
          {  return symbolFactory.newSymbol("Asterisque", UL_Asterisque);  }
        case 200: break;
        case 180: 
          {  return symbolFactory.newSymbol("Type Chaîne", UL_Type_Chaine);  }
        case 201: break;
        case 135: 
          {  return symbolFactory.newSymbol("Enumération", UL_Enumeration);  }
        case 202: break;
        case 116: 
          {  return symbolFactory.newSymbol("Type Entier", UL_Type_Entier);  }
        case 203: break;
        case 16: 
          {  return symbolFactory.newSymbol("Deux Points", UL_Deux_Points);  }
        case 204: break;
        case 26: 
          {  return symbolFactory.newSymbol("Esperluette", UL_Esperluette);  }
        case 205: break;
        case 56: 
          {  return symbolFactory.newSymbol("Double Egal", UL_Double_Egal);  }
        case 206: break;
        case 59: 
          {  return symbolFactory.newSymbol("Double Plus", UL_Double_Plus);  }
        case 207: break;
        case 3: 
        case 4: 
          {   }
        case 208: break;
        case 5: 
        case 6: 
          {  return symbolFactory.newSymbol("Nombre Entier", UL_Nombre_Entier, yytext());  }
        case 209: break;
        case 51: 
        case 93: 
          {  return symbolFactory.newSymbol("Chaine de caractères", UL_Chaine, yytext());  }
        case 210: break;
        case 62: 
          {  return symbolFactory.newSymbol("Double Esperluette", UL_Double_Esperluette);  }
        case 211: break;
        case 159: 
          {  return symbolFactory.newSymbol("Final", UL_Final);  }
        case 212: break;
        case 150: 
          {  return symbolFactory.newSymbol("Class", UL_Class);  }
        case 213: break;
        case 136: 
          {  return symbolFactory.newSymbol("Sinon", UL_Sinon);  }
        case 214: break;
        case 7: 
          {  return symbolFactory.newSymbol("Point", UL_Point);  }
        case 215: break;
        case 23: 
          {  return symbolFactory.newSymbol("Moins", UL_Moins);  }
        case 216: break;
        case 126: 
          {  return symbolFactory.newSymbol("Nul", UL_Nul);  }
        case 217: break;
        case 169: 
          {  return symbolFactory.newSymbol("Enregistrement", UL_Enregistrement);  }
        case 218: break;
        case 94: 
          {  return symbolFactory.newSymbol("Caractère", UL_Caractere, yytext());  }
        case 219: break;
        case 125: 
          {  return symbolFactory.newSymbol("Type Caractère", UL_Type_Caractere);  }
        case 220: break;
        case 58: 
          {  return symbolFactory.newSymbol("Supérieur Egal", UL_Superieur_Egal);  }
        case 221: break;
        case 193: 
          {  return symbolFactory.newSymbol("Abstract", UL_Abstract);  }
        case 222: break;
        case 168: 
          {  return symbolFactory.newSymbol("Tant que", UL_Tant_Que);  }
        case 223: break;
        case 155: 
          {  return symbolFactory.newSymbol("Afficher", UL_Afficher);  }
        case 224: break;
        case 149: 
          {  return symbolFactory.newSymbol("Définition Constante", UL_Definition_Constante);  }
        case 225: break;
        case 14: 
          {  return symbolFactory.newSymbol("Point Virgule", UL_Point_Virgule);  }
        case 226: break;
        case 176: 
          {  return symbolFactory.newSymbol("Retour", UL_Retour);  }
        case 227: break;
        case 174: 
          {  return symbolFactory.newSymbol("Public", UL_Public);  }
        case 228: break;
        case 170: 
          {  return symbolFactory.newSymbol("Static", UL_Static);  }
        case 229: break;
        case 100: 
          {  return symbolFactory.newSymbol("Second", UL_Second);  }
        case 230: break;
        case 195: 
          {  return symbolFactory.newSymbol("Interface", UL_Interface);  }
        case 231: break;
        case 194: 
          {  return symbolFactory.newSymbol("Protected", UL_Protected);  }
        case 232: break;
        case 147: 
          {  return symbolFactory.newSymbol("Type Vide", UL_Type_Vide);  }
        case 233: break;
        case 90: 
        case 91: 
          {  return symbolFactory.newSymbol("Nombre Flottant", UL_Nombre_Flottant, yytext());  }
        case 234: break;
        case 21: 
          {  return symbolFactory.newSymbol("Supérieur", UL_Superieur);  }
        case 235: break;
        case 20: 
          {  return symbolFactory.newSymbol("Inférieur", UL_Inferieur);  }
        case 236: break;
        case 24: 
          {  return symbolFactory.newSymbol("Pour Cent", UL_Pour_Cent);  }
        case 237: break;
        case 182: 
          {  return symbolFactory.newSymbol("Définition Type", UL_Definition_Type);  }
        case 238: break;
        case 13: 
        case 33: 
        case 34: 
        case 35: 
        case 36: 
        case 37: 
        case 38: 
        case 39: 
        case 40: 
        case 41: 
        case 42: 
        case 44: 
        case 45: 
        case 46: 
        case 63: 
        case 64: 
        case 65: 
        case 66: 
        case 67: 
        case 68: 
        case 69: 
        case 70: 
        case 71: 
        case 72: 
        case 73: 
        case 74: 
        case 75: 
        case 76: 
        case 77: 
        case 78: 
        case 79: 
        case 80: 
        case 81: 
        case 82: 
        case 84: 
        case 85: 
        case 87: 
        case 88: 
        case 89: 
        case 95: 
        case 96: 
        case 97: 
        case 99: 
        case 101: 
        case 102: 
        case 103: 
        case 104: 
        case 105: 
        case 106: 
        case 107: 
        case 108: 
        case 109: 
        case 110: 
        case 112: 
        case 113: 
        case 114: 
        case 115: 
        case 117: 
        case 118: 
        case 120: 
        case 121: 
        case 122: 
        case 123: 
        case 124: 
        case 127: 
        case 128: 
        case 129: 
        case 131: 
        case 132: 
        case 133: 
        case 134: 
        case 137: 
        case 138: 
        case 139: 
        case 140: 
        case 141: 
        case 142: 
        case 143: 
        case 144: 
        case 146: 
        case 148: 
        case 151: 
        case 152: 
        case 153: 
        case 154: 
        case 156: 
        case 157: 
        case 158: 
        case 162: 
        case 163: 
        case 164: 
        case 165: 
        case 167: 
        case 171: 
        case 172: 
        case 173: 
        case 175: 
        case 177: 
        case 178: 
        case 179: 
        case 181: 
        case 183: 
        case 186: 
        case 187: 
        case 188: 
        case 190: 
        case 191: 
        case 192: 
        case 196: 
          {  return symbolFactory.newSymbol("Identificateur", UL_Identificateur, yytext());  }
        case 239: break;
        case 57: 
          {  return symbolFactory.newSymbol("Inférieur Egal", UL_Inferieur_Egal);  }
        case 240: break;
        case 83: 
          {  return symbolFactory.newSymbol("Si", UL_Si);  }
        case 241: break;
        case 2: 
        case 10: 
        case 11: 
        case 25: 
          {  emit_warning( "Unrecognized character '" + yytext() + "' -- ignored" );  }
        case 242: break;
        case 12: 
        case 43: 
        case 86: 
        case 119: 
        case 145: 
        case 166: 
          {  return symbolFactory.newSymbol("IdentificateurType", UL_IdentificateurType, yytext());  }
        case 243: break;
        case 27: 
          {  return symbolFactory.newSymbol("Parenthese Ouvrante", UL_Parenthese_Ouvrante);  }
        case 244: break;
        case 28: 
          {  return symbolFactory.newSymbol("Parenthese Fermante", UL_Parenthese_Fermante);  }
        case 245: break;
        case 18: 
          {  return symbolFactory.newSymbol("Point d'Exclamation", UL_Point_Exclamation);  }
        case 246: break;
        case 31: 
          {  return symbolFactory.newSymbol("Crochet Ouvrant", UL_Crochet_Ouvrant);  }
        case 247: break;
        case 32: 
          {  return symbolFactory.newSymbol("Crochet Fermant", UL_Crochet_Fermant);  }
        case 248: break;
        case 185: 
          {  return symbolFactory.newSymbol("Extends", UL_Extends);  }
        case 249: break;
        case 184: 
          {  return symbolFactory.newSymbol("Private", UL_Private);  }
        case 250: break;
        case 111: 
          {  return symbolFactory.newSymbol("Premier", UL_Premier);  }
        case 251: break;
        case 98: 
          {  return symbolFactory.newSymbol("Nouveau", UL_Nouveau);  }
        case 252: break;
        case 15: 
          {  return symbolFactory.newSymbol("Virgule", UL_Virgule);  }
        case 253: break;
        case 8: 
          {  return symbolFactory.newSymbol("Oblique", UL_Oblique);  }
        case 254: break;
        case 29: 
          {  return symbolFactory.newSymbol("Accolade Ouvrante", UL_Accolade_Ouvrante);  }
        case 255: break;
        case 30: 
          {  return symbolFactory.newSymbol("Accolade Fermante", UL_Accolade_Fermante);  }
        case 256: break;
        case 55: 
          {  return symbolFactory.newSymbol("Exclamation Egal", UL_Exclamation_Egal);  }
        case 257: break;
        case 189: 
          {  return symbolFactory.newSymbol("Type Booléen", UL_Type_Booleen);  }
        case 258: break;
        case 160: 
          {  return symbolFactory.newSymbol("Type Entier", UL_Type_Flottant);  }
        case 259: break;
        case 161: 
          {  return symbolFactory.newSymbol("Faux", UL_Faux);  }
        case 260: break;
        case 130: 
          {  return symbolFactory.newSymbol("Vrai", UL_Vrai);  }
        case 261: break;
        case 22: 
          {  return symbolFactory.newSymbol("Plus", UL_Plus);  }
        case 262: break;
        case 19: 
          {  return symbolFactory.newSymbol("Egal", UL_Egal);  }
        case 263: break;
        case 17: 
          {  return symbolFactory.newSymbol("Point d'Interrogation", UL_Point_Interrogation);  }
        case 264: break;
        case 60: 
          {  return symbolFactory.newSymbol("Double Moins", UL_Double_Moins);  }
        case 265: break;
        case 61: 
          {  return symbolFactory.newSymbol("Double Barre", UL_Double_Barre);  }
        case 266: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            yy_do_eof();
              {     return symbolFactory.newSymbol("EOF",sym.EOF);
 }
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }


}
